name: Webhook on Event
# Make sure to change what triggers your action based on your needs
on:
  workflow_call:
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  # ID of our job
  webhook-request:
    # OS to run our job on
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to webhook
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
          "username": "GitHub",
          "content": "@everyone",
          "embeds": [
            {
              "type": "rich",
              "title": "Read to Test",
              "description": "The project ${{ github.repository }} has been deployed.",
              "color": 2123412,
              "thumbnail": {
                "url": "https://business.futureskill.co/fs-logo-light.png"
              },
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor_id }}",
                "icon_url": "https://business.futureskill.co/fs-logo-light.png"
              },
              "url": "https://github.com/${{ github.repository }}"
            }
          ]
          }' ${{ secrets.WEBHOOK_URL }})
          echo "Webhook server response: $RESPONSE"
