name: Webhook on Event
# Make sure to change what triggers your action based on your needs
on:
  workflow_call:
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  # ID of our job
  webhook-request:
    # OS to run our job on
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to webhook
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
          "username": "GitHub",
          "content": "@everyone",
          "embeds": [
            {
              "type": "rich",
              "title": "New Changes",
              "description": "New changes on DroneGPS repository by ${{ github.actor }} {{EVENT_PAYLOAD.repository.full_name }}",
              "color": 2123412,
              "thumbnail": {
                "url": "https://avatars.githubusercontent.com/u/160980408?v=4"
              },
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor_id }}",
                "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
              },
              "url": "https://github.com/***"
            }
          ]
          }' ${{ secrets.WEBHOOK_URL }})
          echo "Webhook server response: $RESPONSE"
          echo {{github}}
